### ISSUE TITLE
profiles links ?

### ISSUE THREAD

**Issue by mcarbonneaux** [nabilbendafi/jsonresume-theme-onepageresume#4]
your template not print profiles links.
i can make PR to that but i'm not sure where to add it.
my first idea if to add at the same place of email and cell with a loop.

**Comment by nabilbendafi** [comment]
Not present in _source_ [One Page Resume](https://css-tricks.com/one-page-resume-site) project, but I think I can manage to update our theme.

**Comment by nabilbendafi** [comment]
Addressed in ad51ee8.

Credit: https://github.com/LinuxBozo/jsonresume-theme-kendall/blob/master/index.js#L52-L104
